### PR TITLE
Fix/ss4 compatible

### PR DESCRIPTION
**Pull request by satrun77**
Update dependencies and YAML config to be compatible with SilverStripe 4 (stable)

### CODE REVIEW

**Comment by stevie-mayhew** [comment]
To be honest I haven't used this for a while. @michalkleiner you seem to be using it a bit so I've added you as a contributor to the project so you can merge and tag as you see fit.

**Comment by michalkleiner** [comment]
Thanks @stevie-mayhew. Are you using something else to achieve a similar thing or do you not have that kind of use case anymore?

**Comment by stevie-mayhew** [comment]
@michalkleiner just haven't had the use case in quite some time! Bet it will pop up next week now I've said this...

**Comment by stevie-mayhew** [comment]
Not quite the next week, but the next month...

**Pull request closed without merging**
